#!/usr/bin/env python3
"""
Seed database with 5 hero heritage sites and sample data.
Run: python scripts/seed_database.py
"""
import asyncio
import uuid
from datetime import datetime
from sqlalchemy.ext.asyncio import AsyncSession
from app.core.database import engine, async_session_maker, init_db
from app.models.site import HeritageSite, ArtifactModel
from app.models.audio_asset import AudioAsset
from app.models.artisan import ArtisanPersona, KnowledgeChunk, ArtisanResponse


HERO_SITES = [
    {
        "id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        "name_vi": "Quan họ Bắc Ninh",
        "name_en": "Quan họ Folk Singing of Bắc Ninh",
        "description_vi": "Quan họ là thể loại dân ca đối đáp đặc trưng của vùng Kinh Bắc, được UNESCO công nhận là Di sản văn hóa phi vật thể đại diện của nhân loại năm 2009.",
        "description_en": "Quan họ is a distinctive antiphonal folk singing genre from the Kinh Bắc region, recognized by UNESCO as Intangible Cultural Heritage of Humanity in 2009.",
        "latitude": 21.1861,
        "longitude": 106.0763,
        "province": "Bắc Ninh",
        "district": "Thành phố Bắc Ninh",
        "heritage_type": "intangible",
        "unesco_status": "inscribed",
        "cultural_layers": ["quan_ho", "bac_ninh", "kinh_bac", "folk_singing", "unesco"],
        "cover_image": "/images/quan-ho-cover.jpg",
        "audio_preview": "/audio/quan-ho-preview.mp3",
        "artifact_model_id": "model-dan-bau",
    },
    {
        "id": "b2c3d4e5-f6a7-8901-bcde-f23456789012",
        "name_vi": "Ca trù Hà Nội",
        "name_en": "Ca trù Singing of Hà Nội",
        "description_vi": "Ca trù là thể loại nghệ thuật diễn xướng phòng cổ truyền thống, được UNESCO công nhận là Di sản văn hóa phi vật thể cần được bảo vệ gấp năm 2009.",
        "description_en": "Ca trù is a traditional chamber music genre, recognized by UNESCO as Intangible Cultural Heritage in Need of Urgent Safeguarding in 2009.",
        "latitude": 21.0285,
        "longitude": 105.8542,
        "province": "Hà Nội",
        "district": "Hoàn Kiếm",
        "heritage_type": "intangible",
        "unesco_status": "inscribed",
        "cultural_layers": ["ca_tru", "ha_noi", "chamber_music", "unesco"],
        "cover_image": "/images/ca-tru-cover.jpg",
        "audio_preview": "/audio/ca-tru-preview.mp3",
        "artifact_model_id": "model-dan-nhi",
    },
    {
        "id": "c3d4e5f6-a7b8-9012-cdef-345678901234",
        "name_vi": "Nhã nhạc Huế",
        "name_en": "Nhuệ Court Music of Huế",
        "description_vi": "Nhã nhạc cung đình Huế là loại nhạc tộc truyền thống của Việt Nam, được UNESCO công nhận là Di sản văn hóa phi vật thể đại diện của nhân loại năm 2003.",
        "description_en": "Nhuệ court music is a traditional Vietnamese court music, recognized by UNESCO as Intangible Cultural Heritage of Humanity in 2003.",
        "latitude": 16.4637,
        "longitude": 107.5909,
        "province": "Thừa Thiên Huế",
        "district": "Thành phố Huế",
        "heritage_type": "intangible",
        "unesco_status": "inscribed",
        "cultural_layers": ["nha_nhac", "hue", "court_music", "unesco", "royal"],
        "cover_image": "/images/nha-nhac-cover.jpg",
        "audio_preview": "/audio/nha-nhac-preview.mp3",
        "artifact_model_id": "model-trong-de",
    },
    {
        "id": "d4e5f6a7-b8c9-0123-defa-456789012345",
        "name_vi": "Đờn ca tài tử",
        "name_en": "Đờn ca tài tử Music of Southern Vietnam",
        "description_vi": "Đờn ca tài tử là nghệ thuật âm nhạc truyền thống của người Nam Bộ, được UNESCO công nhận là Di sản văn hóa phi vật thể đại diện của nhân loại năm 2013.",
        "description_en": "Đờn ca tài tử is a traditional musical art form of Southern Vietnam, recognized by UNESCO as Intangible Cultural Heritage of Humanity in 2013.",
        "latitude": 10.0452,
        "longitude": 105.7469,
        "province": "Cần Thơ",
        "district": "Ninh Kiều",
        "heritage_type": "intangible",
        "unesco_status": "inscribed",
        "cultural_layers": ["don_ca_tai_tu", "mien_nam", "chamber_music", "unesco"],
        "cover_image": "/images/don-ca-tai-tu-cover.jpg",
        "audio_preview": "/audio/don-ca-tai-tu-preview.mp3",
        "artifact_model_id": "model-dan-tranh",
    },
    {
        "id": "e5f6a7b8-c9d0-1234-efab-567890123456",
        "name_vi": "Hò Nghệ An",
        "name_en": "Hò Work Songs of Nghệ An",
        "description_vi": "Hò là thể loại dân ca lao động phổ biến ở vùng Nghệ Tĩnh, phản ánh đời sống sinh hoạt, sản xuất của người dân nơi đây.",
        "description_en": "Hò is a work song folk genre popular in the Nghệ Tĩnh region, reflecting the daily life and production activities of local people.",
        "latitude": 18.6796,
        "longitude": 105.6927,
        "province": "Nghệ An",
        "district": "Thành phố Vinh",
        "heritage_type": "intangible",
        "unesco_status": "national",
        "cultural_layers": ["ho", "nghe_an", "work_songs", "labor", "national"],
        "cover_image": "/images/ho-nghe-an-cover.jpg",
        "audio_preview": "/audio/ho-nghe-an-preview.mp3",
        "artifact_model_id": "model-ao-dai",
    },
]

ARTIFACT_MODELS = [
    {
        "id": "model-dan-bau",
        "name_vi": "Đàn bầu",
        "name_en": "Đàn bầu (Monochord)",
        "description_vi": "Đàn bầu là nhạc cụ dây đơn đặc trưng của Việt Nam, tạo âm nhờ kỹ thuật nẩy, rung, lầy.",
        "description_en": "Đàn bầu is Vietnam's distinctive monochord, producing sound through bending, vibrato, and glissando techniques.",
        "model_url": "/models/dan-bau.glb",
        "scale": "0.5 0.5 0.5",
        "position": "0 0 -1",
    },
    {
        "id": "model-dan-nhi",
        "name_vi": "Đàn nhị",
        "name_en": "Đàn nhị (Two-string Fiddle)",
        "description_vi": "Đàn nhị là nhạc cụ dây hai dây, âm thanh ngân ngon, thường dùng trong Ca trù.",
        "description_en": "Đàn nhị is a two-string fiddle with clear sound, commonly used in Ca trù.",
        "model_url": "/models/dan-nhi.glb",
        "scale": "0.5 0.5 0.5",
        "position": "0 0 -1",
    },
    {
        "id": "model-trong-de",
        "name_vi": "Trống đế",
        "name_en": "Trống đế (Court Drum)",
        "description_vi": "Trống đế là trống lớn dùng trong Nhã nhạc cung đình, tạo âm thanh trầm, dồn dập.",
        "description_en": "Trống đế is a large drum used in Court Music, producing deep, resonant sounds.",
        "model_url": "/models/trong-de.glb",
        "scale": "0.5 0.5 0.5",
        "position": "0 0 -1",
    },
    {
        "id": "model-dan-tranh",
        "name_vi": "Đàn tranh",
        "name_en": "Đàn tranh (16-string Zither)",
        "description_vi": "Đàn tranh là nhạc cụ dây 16 dây, phổ biến trong Đờn ca tài tử.",
        "description_en": "Đàn tranh is a 16-string zither, common in Đờn ca tài tử music.",
        "model_url": "/models/dan-tranh.glb",
        "scale": "0.5 0.5 0.5",
        "position": "0 0 -1",
    },
    {
        "id": "model-ao-dai",
        "name_vi": "Áo dài",
        "name_en": "Áo dài (Traditional Dress)",
        "description_vi": "Áo dài là trang phục truyền thống của người Việt, gợi nhớ đến hình ảnh phụ nữ vùng Nghệ.",
        "description_en": "Áo dài is Vietnam's traditional dress, evoking images of Nghệ An women.",
        "model_url": "/models/ao-dai.glb",
        "scale": "0.5 0.5 0.5",
        "position": "0 0 -1",
    },
]

ARTISAN_PERSONAS = [
    {
        "id": "artisan-quan-ho-01",
        "name_vi": "Bà Nguyễn Thị Hương",
        "name_en": "Mrs. Nguyen Thi Huong",
        "birth_year": 1955,
        "region": "Bắc Ninh",
        "specialty": "quan_ho_singer",
        "bio_vi": "Bà Hương là nghệ nhân Quan họ gạo cội, đã dành trọn đời gắn bó với dòng ca Quan họ Bắc Ninh. Bà từng được phong tặng Nghệ nhân Ưu tú năm 2005.",
        "bio_en": "Mrs. Huong is a master Quan họ artisan who has dedicated her life to Bac Ninh Quan họ singing. She was awarded the title of Meritorious Artisan in 2005.",
        "avatar_url": "/images/artisan-huong.jpg",
        "voice_sample_url": "/audio/artisan-huong-intro.mp3",
    },
    {
        "id": "artisan-ca-tru-01",
        "name_vi": "Thầy Nguyễn Văn Mùi",
        "name_en": "Master Nguyen Van Mui",
        "birth_year": 1948,
        "region": "Hà Nội",
        "specialty": "ca_tru_master",
        "bio_vi": "Thầy Mùi là một trong những người giữ gìn nghệ thuật Ca trù cuối cùng, con trai của nghệ nhân Nguyễn Văn Đao. Thầy đã dạy truyền nghề cho nhiều thế hệ học trò.",
        "bio_en": "Master Mui is one of the last guardians of Ca trù art, son of artisan Nguyen Van Dao. He has taught many generations of students.",
        "avatar_url": "/images/artisan-mui.jpg",
        "voice_sample_url": "/audio/artisan-mui-intro.mp3",
    },
    {
        "id": "artisan-nha-nhac-01",
        "name_vi": "Nghệ nhân Mai Văn Biên",
        "name_en": "Artisan Mai Van Bien",
        "birth_year": 1952,
        "region": "Huế",
        "specialty": "nha_nhac_musician",
        "bio_vi": "Nghệ nhân Biên là người trực tiếp tham gia phục hồi Nhã nhạc Huế sau năm 1990, am hiểu sâu về các chế độ, bài nhạc cung đình.",
        "bio_en": "Artisan Bien directly participated in restoring Hue Court Music after 1990, with deep knowledge of court music modes and repertoire.",
        "avatar_url": "/images/artisan-bien.jpg",
        "voice_sample_url": "/audio/artisan-bien-intro.mp3",
    },
    {
        "id": "artisan-don-ca-01",
        "name_vi": "Bà Trần Thị Kim Loan",
        "name_en": "Mrs. Tran Thi Kim Loan",
        "birth_year": 1960,
        "region": "Cần Thơ",
        "specialty": "don_ca_tai_tu_singer",
        "bio_vi": "Bà Loan là ca sĩ Đờn ca tài tử nổi tiếng miền Tây, từng đoạt giải Nhất cuộc thi Đờn ca tài tử toàn quốc. Bà am hiểu các bài hát cổ, cách trình diễn.",
        "bio_en": "Mrs. Loan is a famous Southern Đờn ca tài tử singer, winner of National First Prize. She knows classical repertoire and performance practices.",
        "avatar_url": "/images/artisan-loan.jpg",
        "voice_sample_url": "/audio/artisan-loan-intro.mp3",
    },
    {
        "id": "artisan-ho-01",
        "name_vi": "Ông Lê Văn Tám",
        "name_en": "Mr. Le Van Tam",
        "birth_year": 1950,
        "region": "Nghệ An",
        "specialty": "ho_singer",
        "bio_vi": "Ông Tám là người lao động, xưởng gốm, cũng là ca sĩ Hò gạo cội. Ông biết nhiều câu Hò đập lúa, Hò giã gạo, Hò kéo còi.",
        "bio_en": "Mr. Tam is a potter and authentic Hò singer. He knows many work songs: rice pounding, rice winnowing, conch pulling Hò.",
        "avatar_url": "/images/artisan-tam.jpg",
        "voice_sample_url": "/audio/artisan-tam-intro.mp3",
    },
]

KNOWLEDGE_CHUNKS = [
    # Quan họ Bắc Ninh - 10 chunks (history: 3, technique: 3, meaning: 2, ritual: 2)
    {
        "id": "chunk-quan-ho-history-1",
        "site_id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        "artisan_persona_id": "artisan-quan-ho-01",
        "category": "history",
        "content_vi": "Quan họ hình thành từ thế kỷ 13, gắn liền với văn hóa làng xã Kinh Bắc. Theo lời người già, Quan họ bắt đầu từ các hội chè trầu, hội văn hóa nơi người trẻ tụ tập hát đòi, hát đối đáp.",
        "content_en": "Quan họ formed in the 13th century, linked to Kinh Bac village culture. Elders say it began at tea and betel gatherings where youth sang call-and-response.",
        "source_type": "unesco",
        "verified_by": "UNESCO Nomination File 2008",
        "verified_at": "2008-11-15",
    },
    {
        "id": "chunk-quan-ho-history-2",
        "site_id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        "artisan_persona_id": "artisan-quan-ho-01",
        "category": "history",
        "content_vi": "Quan họ được truyền từ đời này sang đời qua cách gọi là 'hát lặn' - hát trong lòng mình trước khi phát ra âm thanh. Hình thức này giúp giữ gìn tông đường, điệu bài truyền thống.",
        "content_en": "Quan họ was transmitted through 'hát lặn' - singing inwardly before vocalizing. This form helps preserve melodic lines and traditional song structures.",
        "source_type": "unesco",
        "verified_by": "UNESCO Nomination File 2008",
        "verified_at": "2008-11-15",
    },
    {
        "id": "chunk-quan-ho-history-3",
        "site_id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        "artisan_persona_id": "artisan-quan-ho-01",
        "category": "history",
        "content_vi": "Năm 2009, UNESCO đã công nhận Quan họ là Di sản văn hóa phi vật thể đại diện của nhân loại, ghi nhận giá trị đối thoại văn hóa qua âm nhạc.",
        "content_en": "In 2009, UNESCO recognized Quan họ as Intangible Cultural Heritage of Humanity, acknowledging its cultural dialogue value through music.",
        "source_type": "unesco",
        "verified_by": "UNESCO Official Records",
        "verified_at": "2009-10-07",
    },
    {
        "id": "chunk-quan-ho-technique-1",
        "site_id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        "artisan_persona_id": "artisan-quan-ho-01",
        "category": "technique",
        "content_vi": "Kỹ thuật nẩy hát là đặc trưng nhất của Quan họ: giọng hát bật lên cao đột ngột rồi rơi xuống, tạo cảm xúc mạnh. Kỹ thuật này cần hơi thở tốt và kiểm soát thanh quang chính xác.",
        "content_en": "The nay hat technique is most characteristic of Quan họ: voice suddenly jumps high then falls, creating strong emotion. Requires good breath control and precise vocal fold control.",
        "source_type": "unesco",
        "verified_by": "UNESCO Nomination File 2008",
        "verified_at": "2008-11-15",
    },
    {
        "id": "chunk-quan-ho-technique-2",
        "site_id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        "artisan_persona_id": "artisan-quan-ho-01",
        "category": "technique",
        "content_vi": "Quan họ có 32 cây lụa chính (hoa, thu, đông, hà, tây...) và 66 cây phụ, mỗi cây có điệu riêng biệt. Người hát cần nắm vững cấu trúc âm điệu để phát triển tương đối.",
        "content_en": "Quan họ has 32 main tunes (flower, autumn, east, river, west...) and 66 subsidiary tunes, each with distinct melodic structures.",
        "source_type": "unesco",
        "verified_by": "UNESCO Nomination File 2008",
        "verified_at": "2008-11-15",
    },
    {
        "id": "chunk-quan-ho-technique-3",
        "site_id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        "artisan_persona_id": "artisan-quan-ho-01",
        "category": "technique",
        "content_vi": "Giọng hát trong Quan họ phải có độ trong, âm vang tự nhiên, không dùng micro khi trình diễn truyền thống. Hợp ca cần biết cách 'giao hưởng' - mượp theo giọng của đối thoại.",
        "content_en": "Quan họ singing requires clear, natural resonance without microphones in traditional performance. Hợp ca must know 'giao hưởng' - blending with counterpart's voice.",
        "source_type": "unesco",
        "verified_by": "UNESCO Nomination File 2008",
        "verified_at": "2008-11-15",
    },
    {
        "id": "chunk-quan-ho-meaning-1",
        "site_id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        "artisan_persona_id": "artisan-quan-ho-01",
        "category": "meaning",
        "content_vi": "Trao trầu trong Quan họ không chỉ là lễ phép, mà là biểu tượng của tình cảm chân thành. Câu hát 'Trầu không phải trầu, trầu là lòng' nói lên tất cả.",
        "content_en": "Betel offering in Quan họ is not just etiquette, but symbol of sincere affection. The lyric 'Betel is not betel, betel is the heart' expresses this spirit.",
        "source_type": "unesco",
        "verified_by": "UNESCO Nomination File 2008",
        "verified_at": "2008-11-15",
    },
    {
        "id": "chunk-quan-ho-meaning-2",
        "site_id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        "artisan_persona_id": "artisan-quan-ho-01",
        "category": "meaning",
        "content_vi": "Quan họ phản ám quá trình hẹn hò, yêu ái của người trẻ. Những câu hát như 'Xin mâi tóc' hay 'Xin áo bà ba' là lời ngôn ngữ tình ca nhẹ nhàng, không direct.",
        "content_en": "Quan họ reflects youth courtship. Songs like 'Xin mâi tóc' or 'Xin áo bà ba' are gentle love lyrics, never explicit.",
        "source_type": "unesco",
        "verified_by": "UNESCO Nomination File 2008",
        "verified_at": "2008-11-15",
    },
    {
        "id": "chunk-quan-ho-ritual-1",
        "site_id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        "artisan_persona_id": "artisan-quan-ho-01",
        "category": "ritual",
        "content_vi": "Quan họ được thực hành trong lễ hội Quan họ Bắc Ninh, diễn ra vào đầu tháng giêng âm lịch. Các đôi hợp ca từ hai làng diệt đến vườn hoa, hát qua 16 cây.",
        "content_en": "Quan họ is practiced during the Quan họ Festival of Bắc Ninh, occurring at the beginning of the lunar calendar's first month.",
        "source_type": "unesco",
        "verified_by": "UNESCO Nomination File 2008",
        "verified_at": "2008-11-15",
    },
    {
        "id": "chunk-quan-ho-ritual-2",
        "site_id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        "artisan_persona_id": "artisan-quan-ho-01",
        "category": "ritual",
        "content_vi": "Trong lễ hội, quy tụ nghệ nhân từ các làng chài, làng gốm, làng giấy. Họ cùng nhau thực hành, rèn luyện, và truyền công đường cho thế hệ trẻ.",
        "content_en": "During the festival, artisan masters from craft villages gather to practice, train, and transmit the art to younger generations.",
        "source_type": "unesco",
        "verified_by": "UNESCO Nomination File 2008",
        "verified_at": "2008-11-15",
    },
    # Ca trù Hà Nội - 10 chunks (history: 3, technique: 3, meaning: 2, ritual: 2)
    {
        "id": "chunk-ca-tru-history-1",
        "site_id": "b2c3d4e5-f6a7-8901-bcde-f23456789012",
        "artisan_persona_id": "artisan-ca-tru-01",
        "category": "history",
        "content_vi": "Ca trù ra đời từ thế kỷ 11, ban đầu gọi là 'hát cửa đình' - hát ở cửa nhà thờ làng. Sau này vào cung đình và các hội quán, trở thành nghệ thuật phòng cung tinh tế.",
        "content_en": "Ca trù originated in the 11th century, initially called 'hat cua dinh' - singing at village communal house. Later entered court and guilds, becoming refined chamber art.",
        "source_type": "unesco",
        "verified_by": "UNESCO Nomination File 2003",
        "verified_at": "2003-11-28",
    },
    {
        "id": "chunk-ca-tru-history-2",
        "site_id": "b2c3d4e5-f6a7-8901-bcde-f23456789012",
        "artisan_persona_id": "artisan-ca-tru-01",
        "category": "history",
        "content_vi": "Qua thế kỷ, Ca trù phát triển thành ba trường phái chính: phái phách, phái đàn nhị, và phái sáo. Mỗi phái có phong cách trình diễn riêng biệt.",
        "content_en": "Through centuries, Ca trù developed into three main schools: phach school, dan nhi school, and sao school, each with distinct performance styles.",
        "source_type": "unesco",
        "verified_by": "UNESCO Nomination File 2003",
        "verified_at": "2003-11-28",
    },
    {
        "id": "chunk-ca-tru-history-3",
        "site_id": "b2c3d4e5-f6a7-8901-bcde-f23456789012",
        "artisan_persona_id": "artisan-ca-tru-01",
        "category": "history",
        "content_vi": "Năm 2009, Ca trù được công nhận là Di sản cần bảo vệ gấp, do số lượng nghệ nhân còn lại bằng chục người. Sự tồn tại của nghệ thuật đang bị đe dọa.",
        "content_en": "In 2009, Ca trù was recognized as Urgent Safeguarding heritage due to only dozens of remaining masters, threatening the art's survival.",
        "source_type": "unesco",
        "verified_by": "UNESCO Official Records",
        "verified_at": "2009-09-17",
    },
    {
        "id": "chunk-ca-tru-technique-1",
        "site_id": "b2c3d4e5-f6a7-8901-bcde-f23456789012",
        "artisan_persona_id": "artisan-ca-tru-01",
        "category": "technique",
        "content_vi": "Ca trù có 56 bài hát chính thức (bài thứ, bài nhiều...). Kỹ thuật 'ở' (giọng lắc) và 'ngăn' (giọng thẳng) là hai giọng chính. Phách đánh nhịp, đàn nhị kéo cung.",
        "content_en": "Ca trù has 56 official pieces. Techniques 'o' (vibrato voice) and 'ngan' (straight voice) are two main styles. Phach beats time, dan nhi bows.",
        "source_type": "unesco",
        "verified_by": "UNESCO Nomination File 2003",
        "verified_at": "2003-11-28",
    },
    {
        "id": "chunk-ca-tru-technique-2",
        "site_id": "b2c3d4e5-f6a7-8901-bcde-f23456789012",
        "artisan_persona_id": "artisan-ca-tru-01",
        "category": "technique",
        "content_vi": "Thanh nhì đầu (thanh ran) là kỹ thuật đặc biệt của Ca trù: đầu dây đàn nhị được bám vào miệng phía dưới thanh quang để tạo rung thanh.",
        "content_en": "Thanh nhì đầu (thanh ran) is Ca trù's special technique: the string's top end is bitten by the lower lip to create vocal resonance.",
        "source_type": "unesco",
        "verified_by": "UNESCO Nomination File 2003",
        "verified_at": "2003-11-28",
    },
    {
        "id": "chunk-ca-tru-technique-3",
        "site_id": "b2c3d4e5-f6a7-8901-bcde-f23456789012",
        "artisan_persona_id": "artisan-ca-tru-01",
        "category": "technique",
        "content_vi": "Khi trình diễn, ca sĩ phải ngồi khiêm tốn, thân mình thẳng, mắt nhìn thẳng vào người nghe. Ánh mắt truyền cảm xúc, giao tiếp tâm hồn.",
        "content_en": "During performance, the singer sits humbly with straight posture and direct eye contact. Eyes convey emotion and soul communication.",
        "source_type": "unesco",
        "verified_by": "UNESCO Nomination File 2003",
        "verified_at": "2003-11-28",
    },
    {
        "id": "chunk-ca-tru-meaning-1",
        "site_id": "b2c3d4e5-f6a7-8901-bcde-f23456789012",
        "artisan_persona_id": "artisan-ca-tru-01",
        "category": "meaning",
        "content_vi": "Ca trù là 'hội thoại qua âm nhạc' - mỗi bài hát là một cuộc đối thoại giữa người trình diễn và khách nghe. Khách nghe có thể yêu cầu hát bài tương ứng.",
        "content_en": "Ca trù is 'musical dialogue' - each song is a conversation between performer and guest. Guests may request relevant pieces.",
        "source_type": "unesco",
        "verified_by": "UNESCO Nomination File 2003",
        "verified_at": "2003-11-28",
    },
    {
        "id": "chunk-ca-tru-meaning-2",
        "site_id": "b2c3d4e5-f6a7-8901-bcde-f23456789012",
        "artisan_persona_id": "artisan-ca-tru-01",
        "category": "meaning",
        "content_vi": "Lời hát Ca trù thường thể hiện tình yêu, chuyện tình, hay vinh quang danh vọng. Tinh thần ca tần bằng hơi thở thanh khiết, ít ham danh tiếng.",
        "content_en": "Ca trù lyrics express love, romance, or glory. The artistic spirit values purity over fame-seeking.",
        "source_type": "unesco",
        "verified_by": "UNESCO Nomination File 2003",
        "verified_at": "2003-11-28",
    },
    {
        "id": "chunk-ca-tru-ritual-1",
        "site_id": "b2c3d4e5-f6a7-8901-bcde-f23456789012",
        "artisan_persona_id": "artisan-ca-tru-01",
        "category": "ritual",
        "content_vi": "Ca trù truyền thống được thực hành trong các hội quán Hà Nội. Khách nghe phải tôn trọng, im lặng lắng nghe, sau đó mới khen ngợi.",
        "content_en": "Traditional Ca trù is practiced in Hanoi guildhalls. Guests must listen respectfully and silently before applauding.",
        "source_type": "unesco",
        "verified_by": "UNESCO Nomination File 2003",
        "verified_at": "2003-11-28",
    },
    {
        "id": "chunk-ca-tru-ritual-2",
        "site_id": "b2c3d4e5-f6a7-8901-bcde-f23456789012",
        "artisan_persona_id": "artisan-ca-tru-01",
        "category": "ritual",
        "content_vi": "Buổi hát Ca trù thường bắt đầu bằng nghi lễ trần trình với lạy chùm trầu, đọc điệu hát, xin phép trước. Đây là nghi lễ tôn vương tổ tiên.",
        "content_en": "Ca trù performances begin with a ritual: betel offering, reciting song titles, asking ancestral permission for respect.",
        "source_type": "unesco",
        "verified_by": "UNESCO Nomination File 2003",
        "verified_at": "2003-11-28",
    },
    # Nhã nhạc Huế - 10 chunks (history: 3, technique: 3, meaning: 2, ritual: 2)
    {
        "id": "chunk-nha-nhac-history-1",
        "site_id": "c3d4e5f6-a7b8-9012-cdef-345678901234",
        "artisan_persona_id": "artisan-nha-nhac-01",
        "category": "history",
        "content_vi": "Nhã nhạc Huế xuất hiện từ thế kỷ 17, phát triển mạnh từ thế kỷ 18 dưới triều Nguyễn. Được truyền vào các cung đỉnh, dân ca trong cung.",
        "content_en": "Hue Court Music emerged in the 17th century, flourishing under Nguyễn dynasty from 18th century. Transmitted in royal courts and folk ceremonies.",
        "source_type": "unesco",
        "verified_by": "UNESCO Nomination File 2003",
        "verified_at": "2003-11-07",
    },
    {
        "id": "chunk-nha-nhac-history-2",
        "site_id": "c3d4e5f6-a7b8-9012-cdef-345678901234",
        "artisan_persona_id": "artisan-nha-nhac-01",
        "category": "history",
        "content_vi": "Sau năm 1945, Nhã nhạc suýt chết vì mất đi môi trường cung đình. Những nghệ nhân đã bảo tồn bằng việc học và giảng dạy trong các trường ca mây.",
        "content_en": "After 1945, Court Music nearly perished without its royal court environment. Masters preserved it through teaching at traditional arts schools.",
        "source_type": "unesco",
        "verified_by": "UNESCO Nomination File 2003",
        "verified_at": "2003-11-07",
    },
    {
        "id": "chunk-nha-nhac-history-3",
        "site_id": "c3d4e5f6-a7b8-9012-cdef-345678901234",
        "artisan_persona_id": "artisan-nha-nhac-01",
        "category": "history",
        "content_vi": "Năm 2001, Việt Nam đã đề nghị UNESCO công nhận Nhã nhạc Huế với 208 hội thoại, bản giao hưởng, và 64 video tài liệu.",
        "content_en": "In 2001, Vietnam submitted the nomination to UNESCO with 208 musical pieces, scores, and 64 documentary videos.",
        "source_type": "unesco",
        "verified_by": "UNESCO Official Records",
        "verified_at": "2003-11-07",
    },
    {
        "id": "chunk-nha-nhac-technique-1",
        "site_id": "c3d4e5f6-a7b8-9012-cdef-345678901234",
        "artisan_persona_id": "artisan-nha-nhac-01",
        "category": "technique",
        "content_vi": "Nhã nhạc có 12 chế độ cung đình (Giao thiên, Tế tổ, Triều hội...). Mỗi chế độ có bài nhạc, nhịp, điều khắc quy định chặt chẽ theo Nho giáo.",
        "content_en": "Court music has 12 court modes (Heaven worship, Ancestor worship, Court audience...). Each mode has prescribed pieces, rhythms, rules per Confucian principles.",
        "source_type": "unesco",
        "verified_by": "UNESCO Nomination File 2003",
        "verified_at": "2003-11-07",
    },
    {
        "id": "chunk-nha-nhac-technique-2",
        "site_id": "c3d4e5f6-a7b8-9012-cdef-345678901234",
        "artisan_persona_id": "artisan-nha-nhac-01",
        "category": "technique",
        "content_vi": "Nhạc cụ trong Nhã nhạc bao gồm: đàn bầu, đàn tranh, đàn nguyệt, sáo trúc, trống đế, trong chầu. Mỗi nhạc cụ có vai trò riêng trong quy hoạch âm thanh.",
        "content_en": "Court music instruments include: đàn bầu, đàn tranh, đàn nguyệt, sáo trúc, trống đế, trong chầu, each with specific sonic roles.",
        "source_type": "unesco",
        "verified_by": "UNESCO Nomination File 2003",
        "verified_at": "2003-11-07",
    },
    {
        "id": "chunk-nha-nhac-technique-3",
        "site_id": "c3d4e5f6-a7b8-9012-cdef-345678901234",
        "artisan_persona_id": "artisan-nha-nhac-01",
        "category": "technique",
        "content_vi": "Kỹ thuật hát Nhã nhạc cần tuệ hát tinh tế, hơi thở điều hoà, âm vang phải hòa quyện với nhạc cụ. Giọng hát không được cất quá mức.",
        "content_en": "Court music singing requires refined vocal technique, controlled breathing, and resonance blending with instruments. Voice must not overpower.",
        "source_type": "unesco",
        "verified_by": "UNESCO Nomination File 2003",
        "verified_at": "2003-11-07",
    },
    {
        "id": "chunk-nha-nhac-meaning-1",
        "site_id": "c3d4e5f6-a7b8-9012-cdef-345678901234",
        "artisan_persona_id": "artisan-nha-nhac-01",
        "category": "meaning",
        "content_vi": "Nhã nhạc tượng trưng cho sự bình yên của thiên đàng, sức mạnh của trời đất, và trật tự của xã hội. Duy nhất phương Đông có nghệ thuật này.",
        "content_en": "Court music symbolizes heavenly peace, earthly power, and social order. This art form is unique to East Asia.",
        "source_type": "unesco",
        "verified_by": "UNESCO Nomination File 2003",
        "verified_at": "2003-11-07",
    },
    {
        "id": "chunk-nha-nhac-meaning-2",
        "site_id": "c3d4e5f6-a7b8-9012-cdef-345678901234",
        "artisan_persona_id": "artisan-nha-nhac-01",
        "category": "meaning",
        "content_vi": "Dòng nhạc Nhã nhạc mang tính truyền giáo, thể hiện triết lý Nho giáo qua âm nhạc. Mỗi nốt nhạc đều có ý nghĩa tâm linh sâu sắc.",
        "content_en": "Court Music carries educational and Confucian philosophical values. Every musical note has deep spiritual meaning.",
        "source_type": "unesco",
        "verified_by": "UNESCO Nomination File 2003",
        "verified_at": "2003-11-07",
    },
    {
        "id": "chunk-nha-nhac-ritual-1",
        "site_id": "c3d4e5f6-a7b8-9012-cdef-345678901234",
        "artisan_persona_id": "artisan-nha-nhac-01",
        "category": "ritual",
        "content_vi": "Nhã nhạc được trình diễn trong các lễ hội quan họ, lễ triều tiên, và lễ cúng vua. Việc thực hành chứa đựng giá trị tâm linh quốc gia.",
        "content_en": "Court Music performs at heritage festivals, annual ceremonies, and royal worship rituals, embodying national spiritual values.",
        "source_type": "unesco",
        "verified_by": "UNESCO Nomination File 2003",
        "verified_at": "2003-11-07",
    },
    {
        "id": "chunk-nha-nhac-ritual-2",
        "site_id": "c3d4e5f6-a7b8-9012-cdef-345678901234",
        "artisan_persona_id": "artisan-nha-nhac-01",
        "category": "ritual",
        "content_vi": "Buổi biểu diễn Nhã nhạc cần đi kèm với múa lân, múa voi, múa tượng. Ba nghệ thuật này tạo thành tứ đại hội trong Hoàng gia.",
        "content_en": "Court Music performances include lion dance, elephant dance, and lantern dance, forming the royal cultural quartet.",
        "source_type": "unesco",
        "verified_by": "UNESCO Nomination File 2003",
        "verified_at": "2003-11-07",
    },
    # Đờn ca tài tử - 10 chunks (history: 3, technique: 3, meaning: 2, ritual: 2)
    {
        "id": "chunk-don-ca-history-1",
        "site_id": "d4e5f6a7-b8c9-0123-defa-456789012345",
        "artisan_persona_id": "artisan-don-ca-01",
        "category": "history",
        "content_vi": "Đờn ca tài tử xuất hiện từ thế kỷ 18 tại miền Tây sông Cửu Long. Nghệ thuật phát triển từ các buổi ca nhạc gia đình và hội hè.",
        "content_en": "Don ca tai tu emerged in the 18th century in the Mekong Delta. The art developed from family music sessions and summer festivals.",
        "source_type": "unesco",
        "verified_by": "UNESCO Nomination File 2013",
        "verified_at": "2013-11-21",
    },
    {
        "id": "chunk-don-ca-history-2",
        "site_id": "d4e5f6a7-b8c9-0123-defa-456789012345",
        "artisan_persona_id": "artisan-don-ca-01",
        "category": "history",
        "content_vi": "Sau chiến tranh, nghệ thuật Đờn ca tài tử có nguy cơ mai một. Các nghệ nhân đã cùng nhau thành lập trường ca để truyền bản.",
        "content_en": "After war, Don ca tai tu faced extinction risk. Masters founded traditional arts schools to preserve the heritage.",
        "source_type": "unesco",
        "verified_by": "UNESCO Nomination File 2013",
        "verified_at": "2013-11-21",
    },
    {
        "id": "chunk-don-ca-history-3",
        "site_id": "d4e5f6a7-b8c9-0123-defa-456789012345",
        "artisan_persona_id": "artisan-don-ca-01",
        "category": "history",
        "content_vi": "Năm 2013, UNESCO công nhận Đờn ca tài tử là Di sản văn hóa phi vật thể đại diện của nhân loại, ghi nhận giá trị sáng tạo bất diệt.",
        "content_en": "In 2013, UNESCO recognized Don ca tai tu as Intangible Cultural Heritage of Humanity for its creative and improvisational essence.",
        "source_type": "unesco",
        "verified_by": "UNESCO Official Records",
        "verified_at": "2013-11-21",
    },
    {
        "id": "chunk-don-ca-technique-1",
        "site_id": "d4e5f6a7-b8c9-0123-defa-456789012345",
        "artisan_persona_id": "artisan-don-ca-01",
        "category": "technique",
        "content_vi": "Đờn ca tài tử có 20 bài gốc (bài tố, bài nhạc...). Nghệ thuật immediate (sáng tác ngay) là đặc trưng: nghệ sĩ即兴 biến tấu trên khung bài cố định.",
        "content_en": "Don ca tai tu has 20 principal pieces. Improvisation is characteristic: artists spontaneously vary on fixed piece structures.",
        "source_type": "unesco",
        "verified_by": "UNESCO Nomination File 2013",
        "verified_at": "2013-11-21",
    },
    {
        "id": "chunk-don-ca-technique-2",
        "site_id": "d4e5f6a7-b8c9-0123-defa-456789012345",
        "artisan_persona_id": "artisan-don-ca-01",
        "category": "technique",
        "content_vi": "Thanh điệu Đờn ca tài tử cần biết cách 'lấy hơi' - hít sâu từ đáy ngực để tạo hơi thanh mạnh mẽ. Kỹ thuật này tạo âm sâu, tràn đầy cảm xúc.",
        "content_en": "Don ca tai tu requires 'breath taking' technique - deep inhalation from the chest for powerful, emotional resonance.",
        "source_type": "unesco",
        "verified_by": "UNESCO Nomination File 2013",
        "verified_at": "2013-11-21",
    },
    {
        "id": "chunk-don-ca-technique-3",
        "site_id": "d4e5f6a7-b8c9-0123-defa-456789012345",
        "artisan_persona_id": "artisan-don-ca-01",
        "category": "technique",
        "content_vi": "Một bản nhạc Đờn ca tài tử cần có 'khung' (điệu sở), 'chiều' (điệu chiều) và 'đánh' (cách đàn). Ba yếu tố này tạo nên tấm điệp tài tình.",
        "content_en": "Don ca tai tu pieces need 'khung' (main tune), 'chiều' (response), and 'đánh' (instrumental pattern) - the artistic triangle.",
        "source_type": "unesco",
        "verified_by": "UNESCO Nomination File 2013",
        "verified_at": "2013-11-21",
    },
    {
        "id": "chunk-don-ca-meaning-1",
        "site_id": "d4e5f6a7-b8c9-0123-defa-456789012345",
        "artisan_persona_id": "artisan-don-ca-01",
        "category": "meaning",
        "content_vi": "Đờn ca tài tử phản ánh tâm tình dân gian miền Tây sông nước. Những câu hát về tình yêu, chia ly, hoạn khản như nước tây bằng sông.",
        "content_en": "Don ca tai tu reflects Southern Mekong Delta folk sentiments - love, separation, sorrow flow like river waters.",
        "source_type": "unesco",
        "verified_by": "UNESCO Nomination File 2013",
        "verified_at": "2013-11-21",
    },
    {
        "id": "chunk-don-ca-meaning-2",
        "site_id": "d4e5f6a7-b8c9-0123-defa-456789012345",
        "artisan_persona_id": "artisan-don-ca-01",
        "category": "meaning",
        "content_vi": "Tên gọi 'tài tử' chỉ con người tài hoa, 'tài' chỉ nghệ thuật, 'tử' chỉ con người. Nghệ sĩ phải là người có tài và tử cách.",
        "content_en": "'Tai tu' name signifies artistic excellence - 'tai' for art, 'tu' for person. Artists must possess both skill and virtue.",
        "source_type": "unesco",
        "verified_by": "UNESCO Nomination File 2013",
        "verified_at": "2013-11-21",
    },
    {
        "id": "chunk-don-ca-ritual-1",
        "site_id": "d4e5f6a7-b8c9-0123-defa-456789012345",
        "artisan_persona_id": "artisan-don-ca-01",
        "category": "ritual",
        "content_vi": "Đờn ca tài tử được thực hành trong các hội hè làng xóm, lễ hội trung thu, và đám cưới truyền thống. Buổi hòa nhạc thường kéo dài cả đêm.",
        "content_en": "Don ca tai tu performs at village festivals, Mid-Autumn celebrations, and traditional weddings, often lasting entire nights.",
        "source_type": "unesco",
        "verified_by": "UNESCO Nomination File 2013",
        "verified_at": "2013-11-21",
    },
    {
        "id": "chunk-don-ca-ritual-2",
        "site_id": "d4e5f6a7-b8c9-0123-defa-456789012345",
        "artisan_persona_id": "artisan-don-ca-01",
        "category": "ritual",
        "content_vi": "Khi trình diễn, nghệ sĩ phải xin phép hồn về trước. Buổi hòa nhạc mở đầu bằng việc kỳ vị, xin điệu, và chùm trầu hương.",
        "content_en": "Performers must seek ancestral permission beforehand. Performances open with seating rites, tune requests, and incense offerings.",
        "source_type": "unesco",
        "verified_by": "UNESCO Nomination File 2013",
        "verified_at": "2013-11-21",
    },
    # Hò Nghệ An - 10 chunks (history: 3, technique: 3, meaning: 2, ritual: 2)
    {
        "id": "chunk-ho-history-1",
        "site_id": "e5f6a7b8-c9d0-1234-efab-567890123456",
        "artisan_persona_id": "artisan-ho-01",
        "category": "history",
        "content_vi": "Hò Nghệ An có từ thời kỳ trấn thành, phát triển mạnh từ thế kỷ 16. Là thể loại hát khoe sở, hát công việc nông nghiệp.",
        "content_en": "Nghệ An Hò dates back to early settlement, flourishing from 16th century. A form of work songs for agricultural labor.",
        "source_type": "unesco",
        "verified_by": "Vietnam National Inventory",
        "verified_at": "2022-03-15",
    },
    {
        "id": "chunk-ho-history-2",
        "site_id": "e5f6a7b8-c9d0-1234-efab-567890123456",
        "artisan_persona_id": "artisan-ho-01",
        "category": "history",
        "content_vi": "Hò phát triển từ lớp địa chủ, thợ rèn, thợ gốm thành làng cũng có lễ hội riêng. Mỗi làng có hò đặc trưng, tự bạch nhau.",
        "content_en": "Hò developed among landlords, blacksmiths, and potters. Each craft village has distinctive hò, different from others.",
        "source_type": "unesco",
        "verified_by": "Vietnam National Inventory",
        "verified_at": "2022-03-15",
    },
    {
        "id": "chunk-ho-history-3",
        "site_id": "e5f6a7b8-c9d0-1234-efab-567890123456",
        "artisan_persona_id": "artisan-ho-01",
        "category": "history",
        "content_vi": "Năm 2019, Hò được công nhận là Di sản văn hóa phi vật thể quốc gia. Các làng chài đã duy trì hò kể vụng về biển.",
        "content_en": "In 2019, Hò was recognized as National Intangible Cultural Heritage. Fishing villages maintain hò for ocean voyages.",
        "source_type": "unesco",
        "verified_by": "Ministry of Culture Sports and Tourism",
        "verified_at": "2019-07-12",
    },
    {
        "id": "chunk-ho-technique-1",
        "site_id": "e5f6a7b8-c9d0-1234-efab-567890123456",
        "artisan_persona_id": "artisan-ho-01",
        "category": "technique",
        "content_vi": "Hò được hát theo hai cách: hò đối (2 người đối đáp) và hò đồng (nhiều người hát chung). Cả hai đều cần giao tiếp hòa âm.",
        "content_en": "Hò has two forms: hò đối (call-response by two) and hò đồng (group singing). Both require harmonic communication.",
        "source_type": "unesco",
        "verified_by": "Vietnam National Inventory",
        "verified_at": "2022-03-15",
    },
    {
        "id": "chunk-ho-technique-2",
        "site_id": "e5f6a7b8-c9d0-1234-efab-567890123456",
        "artisan_persona_id": "artisan-ho-01",
        "category": "technique",
        "content_vi": "Giọng hát Hò phải mạnh mẽ, ổn định để vượt được tiếng công cụ. Người hát không dùng mic mà tạo hơi ầm ầm tự nhiên.",
        "content_en": "Hò singing must be strong and steady to compete with tool sounds. No microphones used, natural resonance created.",
        "source_type": "unesco",
        "verified_by": "Vietnam National Inventory",
        "verified_at": "2022-03-15",
    },
    {
        "id": "chunk-ho-technique-3",
        "site_id": "e5f6a7b8-c9d0-1234-efab-567890123456",
        "artisan_persona_id": "artisan-ho-01",
        "category": "technique",
        "content_vi": "Nhịp điệu Hò thường dựa vào nhịp công việc: cầm cù, gõ còi, đập lúa. Người hát phải biết cách 'bám gió' - theo nhịp công cụ.",
        "content_en": "Hò rhythm follows work patterns: rice husking, conch blowing, rice pounding. Singers must 'follow the wind' - sync with tools.",
        "source_type": "unesco",
        "verified_by": "Vietnam National Inventory",
        "verified_at": "2022-03-15",
    },
    {
        "id": "chunk-ho-meaning-1",
        "site_id": "e5f6a7b8-c9d0-1234-efab-567890123456",
        "artisan_persona_id": "artisan-ho-01",
        "category": "meaning",
        "content_vi": "Hò là tiếng nói của người lao động nông thôn. Nó thể hiện khát vọng sống, tình cảm đồng quê, và lòng yêu nước sâu sắc.",
        "content_en": "Hò is the voice of rural workers. It expresses life aspirations, countryside sentiments, and deep patriotism.",
        "source_type": "unesco",
        "verified_by": "Vietnam National Inventory",
        "verified_at": "2022-03-15",
    },
    {
        "id": "chunk-ho-meaning-2",
        "site_id": "e5f6a7b8-c9d0-1234-efab-567890123456",
        "artisan_persona_id": "artisan-ho-01",
        "category": "meaning",
        "content_vi": "Lời hò thường là thư pháp của người dân. Chúng không chỉ giao tiếp mà còn là lời thoại, lời phúc, lời rao đồng.",
        "content_en": "Hò lyrics are folk poetry. Beyond communication, they serve as recitations, blessings, and village announcements.",
        "source_type": "unesco",
        "verified_by": "Vietnam National Inventory",
        "verified_at": "2022-03-15",
    },
    {
        "id": "chunk-ho-ritual-1",
        "site_id": "e5f6a7b8-c9d0-1234-efab-567890123456",
        "artisan_persona_id": "artisan-ho-01",
        "category": "ritual",
        "content_vi": "Hò được hát vào lúc mặt trời mọc, khi đồng ruộng bừng tỏa sương. Đây là khoảnh khắc 'sống' nhất trong ngày.",
        "content_en": "Hò sings at sunrise when rice fields emerge from mist. The most 'alive' moment of the day.",
        "source_type": "unesco",
        "verified_by": "Vietnam National Inventory",
        "verified_at": "2022-03-15",
    },
    {
        "id": "chunk-ho-ritual-2",
        "site_id": "e5f6a7b8-c9d0-1234-efab-567890123456",
        "artisan_persona_id": "artisan-ho-01",
        "category": "ritual",
        "content_vi": "Trong dịp tết, Hò được 'mở đàn' đầu năm. Người già dẫn điệu, trẻ em học hỏi. Đây là nghi lễ truyền thống.",
        "content_en": "During Tet, Hò opens the new year. Elders lead melodic lines while children learn. This is a traditional rite.",
        "source_type": "unesco",
        "verified_by": "Vietnam National Inventory",
        "verified_at": "2022-03-15",
    },
]

PRE_RECORDED_RESPONSES = [
    # Quan họ - 2 responses
    {
        "id": "resp-quan-ho-origin",
        "persona_id": "artisan-quan-ho-01",
        "question_intent": "origin of quan ho",
        "question_vi": "Quan họ bắt nguồn từ đâu?",
        "question_en": "Where does Quan họ originate from?",
        "answer_vi": "Theo lời các bậc tiền bối, Quan họ hình thành từ thế kỷ 13 tại vùng Kinh Bắc, bắt đầu từ các hội chè trầu nơi người trẻ hát đối đáp.",
        "answer_en": "According to elders, Quan họ formed in the 13th century in the Kinh Bac region, starting from tea gatherings where youth sang call-and-response.",
        "audio_url_vi": "/audio/response-quan-ho-origin-vi.mp3",
        "audio_url_en": "/audio/response-quan-ho-origin-en.mp3",
        "confidence": 1.0,
        "citations": ["chunk-quan-ho-history-1"],
    },
    {
        "id": "resp-quan-ho-betel",
        "persona_id": "artisan-quan-ho-01",
        "question_intent": "why betel in quan ho",
        "question_vi": "Tại sao hát Quan họ phải trao trầu?",
        "question_en": "Why is betel exchanged in Quan họ?",
        "answer_vi": "Trầu trân là lễ nghĩa, biểu tượng của tình cảm chân thành. Câu hát 'Trầu không phải trầu, trầu là lòng' nói lên tất cả.",
        "answer_en": "Betel is etiquette, symbol of sincere affection. The lyric 'Betel is not betel, betel is the heart' says it all.",
        "audio_url_vi": "/audio/response-quan-ho-betel-vi.mp3",
        "audio_url_en": "/audio/response-quan-ho-betel-en.mp3",
        "confidence": 1.0,
        "citations": ["chunk-quan-ho-meaning-1"],
    },
    # Ca trù - 2 responses
    {
        "id": "resp-ca-tru-instruments",
        "persona_id": "artisan-ca-tru-01",
        "question_intent": "ca tru instruments",
        "question_vi": "Ca trù dùng nhạc cụ gì?",
        "question_en": "What instruments are used in Ca trù?",
        "answer_vi": "Ca trù dùng phách (gõ nhịp), đàn nhị (kéo cung), và sáo (thỉnh thoảng). Ba nhạc cụ này tạo nên âm màu đặc trưng 'phách - nhị - sáo'.",
        "answer_en": "Ca trù uses phach (beat), dan nhi (bowed), and sao (flute occasionally). These three create the signature 'phach-nhi-sao' timbre.",
        "audio_url_vi": "/audio/response-ca-tru-instruments-vi.mp3",
        "audio_url_en": "/audio/response-ca-tru-instruments-en.mp3",
        "confidence": 1.0,
        "citations": ["chunk-ca-tru-technique-1"],
    },
    {
        "id": "resp-ca-tru-performance",
        "persona_id": "artisan-ca-tru-01",
        "question_intent": "ca tru performance style",
        "question_vi": "Ca trù được trình diễn như thế nào?",
        "question_en": "How is Ca trù performed?",
        "answer_vi": "Ca trù là 'hội thoại qua âm nhạc'. Ca sĩ ngồi thẳng, ánh mắt truyền cảm xúc, giọng hát phải hòa quyện với phách và đàn nhị.",
        "answer_en": "Ca trù is 'musical dialogue'. The singer sits upright, eyes convey emotion, voice blends with phach and dan nhi accompaniment.",
        "audio_url_vi": "/audio/response-ca-tru-performance-vi.mp3",
        "audio_url_en": "/audio/response-ca-tru-performance-en.mp3",
        "confidence": 1.0,
        "citations": ["chunk-ca-tru-meaning-1", "chunk-ca-tru-technique-1"],
    },
    # Nhã nhạc - 2 responses
    {
        "id": "resp-nha-nhac-modes",
        "persona_id": "artisan-nha-nhac-01",
        "question_intent": "nha nhac modes",
        "question_vi": "Nhã nhạc có bao nhiêu chế độ?",
        "question_en": "How many modes does Court Music have?",
        "answer_vi": "Nhã nhạc cung đình có 12 chế độ chính, mỗi chế độ ứng với một nghi lễ cụ thể như Giao thiên, Tế tổ, Triều hội.",
        "answer_en": "Court Music has 12 principal modes, each corresponding to a specific ritual like Heaven Worship, Ancestor Worship, Court Audience.",
        "audio_url_vi": "/audio/response-nha-nhac-modes-vi.mp3",
        "audio_url_en": "/audio/response-nha-nhac-modes-en.mp3",
        "confidence": 1.0,
        "citations": ["chunk-nha-nhac-technique-1"],
    },
    {
        "id": "resp-nha-nhac-instruments",
        "persona_id": "artisan-nha-nhac-01",
        "question_intent": "nha nhac instruments",
        "question_vi": "Nhã nhạc dùng nhạc cụ gì?",
        "question_en": "What instruments are used in Court Music?",
        "answer_vi": "Nhã nhạc dùng đàn bầu, đàn tranh, đàn nguyệt, sáo trúc, trống đế, trong chầu. Mỗi nhạc cụ có vai trò riêng trong âm sắc cung đình.",
        "answer_en": "Court Music uses đàn bầu, đàn tranh, đàn nguyệt, sáo trúc, trống đế, trong chầu - each with distinct court sonic roles.",
        "audio_url_vi": "/audio/response-nha-nhac-instruments-vi.mp3",
        "audio_url_en": "/audio/response-nha-nhac-instruments-en.mp3",
        "confidence": 1.0,
        "citations": ["chunk-nha-nhac-technique-2"],
    },
    # Đờn ca tài tử - 2 responses
    {
        "id": "resp-don-ca-improv",
        "persona_id": "artisan-don-ca-01",
        "question_intent": "don ca tai tu improvisation",
        "question_vi": "Đờn ca tài tử có improvisation không?",
        "question_en": "Does Don ca tai tu have improvisation?",
        "answer_vi": "Có, nghệ thuật immediate (sáng tác ngay) là đặc trưng của Đờn ca tài tử. Nghệ sĩ immediate biến tấu trên khung 20 bài gốc.",
        "answer_en": "Yes, immediate improvisation is characteristic. Artists spontaneously vary on the 20 principal piece frameworks.",
        "audio_url_vi": "/audio/response-don-ca-improv-vi.mp3",
        "audio_url_en": "/audio/response-don-ca-improv-en.mp3",
        "confidence": 1.0,
        "citations": ["chunk-don-ca-technique-1"],
    },
    {
        "id": "resp-don-ca-voice",
        "persona_id": "artisan-don-ca-01",
        "question_intent": "don ca tai tu vocal",
        "question_vi": "Giọng hát Đờn ca tài tử có đặc điểm gì?",
        "question_en": "What characterizes Don ca tai tu vocal style?",
        "answer_vi": "Thanh điệu Đờn ca tài tử cần biết cách 'lấy hơi' - hít sâu từ đáy ngực để tạo hơi thanh mạnh mẽ, tràn đầy cảm xúc.",
        "answer_en": "Don ca tai tu requires 'breath taking' - deep inhalation from the chest for strong, emotional resonance.",
        "audio_url_vi": "/audio/response-don-ca-voice-vi.mp3",
        "audio_url_en": "/audio/response-don-ca-voice-en.mp3",
        "confidence": 1.0,
        "citations": ["chunk-don-ca-technique-2"],
    },
    # Hò Nghệ An - 2 responses
    {
        "id": "resp-ho-types",
        "persona_id": "artisan-ho-01",
        "question_intent": "ho nghe an types",
        "question_vi": "Hò Nghệ An có những loại nào?",
        "question_en": "What types of Nghe An Ho exist?",
        "answer_vi": "Hò Nghệ An có nhiều loại: Hò đập lúa, Hò giã gạo, Hò kéo còi, Hò hái chè... Mỗi loại gắn với một hoạt động lao động cụ thể.",
        "answer_en": "Nghệ An Ho has many types: rice pounding, rice winnowing, conch pulling, tea picking... Each links to a specific labor activity.",
        "audio_url_vi": "/audio/response-ho-types-vi.mp3",
        "audio_url_en": "/audio/response-ho-types-en.mp3",
        "confidence": 1.0,
        "citations": ["chunk-ho-technique-1"],
    },
    {
        "id": "resp-ho-history",
        "persona_id": "artisan-ho-01",
        "question_intent": "ho nghe an history",
        "question_vi": "Hò Nghệ An có từ khi nào?",
        "question_en": "When did Nghệ An Ho originate?",
        "answer_vi": "Hò Nghệ An có từ thời kỳ trấn thành, phát triển mạnh từ thế kỷ 16. Là thể loại hát khoe sở, hát công việc nông nghiệp.",
        "answer_en": "Nghệ An Hò dates from early settlement, flourishing from 16th century. A form of work songs for agricultural labor.",
        "audio_url_vi": "/audio/response-ho-history-vi.mp3",
        "audio_url_en": "/audio/response-ho-history-en.mp3",
        "confidence": 1.0,
        "citations": ["chunk-ho-history-1"],
    },
]


async def seed_database():
    print("Initializing database...")
    await init_db()
    
    async with async_session_maker() as db:
        # Seed Artifact Models
        print("Seeding artifact models...")
        for model_data in ARTIFACT_MODELS:
            model = ArtifactModel(**model_data)
            db.add(model)
        
        # Seed Heritage Sites
        print("Seeding heritage sites...")
        for site_data in HERO_SITES:
            site = HeritageSite(**site_data)
            db.add(site)
        
        # Seed Artisan Personas
        print("Seeding artisan personas...")
        for persona_data in ARTISAN_PERSONAS:
            persona = ArtisanPersona(**persona_data)
            db.add(persona)
        
        # Seed Knowledge Chunks
        print("Seeding knowledge chunks...")
        for chunk_data in KNOWLEDGE_CHUNKS:
            chunk = KnowledgeChunk(**chunk_data)
            db.add(chunk)
        
        # Seed Pre-recorded Responses
        print("Seeding pre-recorded responses...")
        for resp_data in PRE_RECORDED_RESPONSES:
            resp = ArtisanResponse(**resp_data)
            db.add(resp)
        
        await db.commit()
        print("Database seeded successfully!")


if __name__ == "__main__":
    asyncio.run(seed_database())