/* ═══════════════════════════════════════════════════════════
   LOCATION TRANSLATIONS — Vietnamese → English
   Used to display treasure locations in English mode.
   Keys must match the `location` strings in national_treasures.js.
   ═══════════════════════════════════════════════════════════ */
const LOCATION_EN = {
  "Ban Quản lý Di tích Văn hóa Óc Eo, tỉnh An Giang": "Óc Eo Cultural Relic Management Board, An Giang Province",
  "Ban Quản lý di tích Văn hóa Óc Eo, tỉnh An Giang": "Óc Eo Cultural Relic Management Board, An Giang Province",
  "Ban Quản lý di tích và du lịch Mỹ Sơn, tỉnh Quảng Nam": "Mỹ Sơn Relic and Tourism Management Board, Quảng Nam Province",
  "Bảo tàng Chiến dịch Hồ Chí Minh, Hồ Chí Minh City": "Hồ Chí Minh Campaign Museum, Ho Chi Minh City",
  "Bảo tàng Cổ vật Cung đình Huế": "Hue Royal Antiquities Museum",
  "Bảo tàng Cổ vật Cung đình Huế, Thừa Thiên Huế": "Hue Royal Antiquities Museum, Thừa Thiên Huế",
  "Bảo tàng Cổ vật Cung đình Huế, tỉnh Thừa Thiên Huế": "Hue Royal Antiquities Museum, Thừa Thiên Huế Province",
  "Bảo tàng Gốm thời dựng nước, TP Hồ Chí Minh": "Museum of Ancient Ceramics, Ho Chi Minh City",
  "Bảo tàng Hoàng gia Nam Hồng, thành phố Từ Sơn, tỉnh Bắc Ninh": "Nam Hồng Royal Museum, Từ Sơn City, Bắc Ninh Province",
  "Bảo tàng Hoàng gia Nam Hồng, tỉnh Bắc Ninh": "Nam Hồng Royal Museum, Bắc Ninh Province",
  "Bảo tàng Hà Nội": "Hanoi Museum",
  "Bảo tàng Hùng Vương, tỉnh Phú Thọ": "Hùng Vương Museum, Phú Thọ Province",
  "Bảo tàng Hải Phòng": "Hai Phong Museum",
  "Bảo tàng Hải quân": "Vietnam Naval Museum",
  "Bảo tàng Hậu Cần, Hà Nội": "Military Logistics Museum, Hanoi",
  "Bảo tàng Hồ Chí Minh, Hà Nội": "Ho Chi Minh Museum, Hanoi",
  "Bảo tàng Kính Hoa, Hà Nội": "Kính Hoa Museum, Hanoi",
  "Bảo tàng Lịch sử Thừa Thiên - Huế": "Thừa Thiên Huế History Museum",
  "Bảo tàng Lịch sử quân sự Việt Nam, Hà Nội": "Vietnam Military History Museum, Hanoi",
  "Bảo tàng Lịch sử quốc gia, Hà Nội": "Vietnam National Museum of History, Hanoi",
  "Bảo tàng Lịch sử thành phố Hồ Chí Minh": "Museum of Vietnamese History, Ho Chi Minh City",
  "Bảo tàng Mỹ thuật Thành phố Hồ Chí Minh": "Ho Chi Minh City Museum of Fine Arts",
  "Bảo tàng Mỹ thuật Việt Nam, Hà Nội": "Vietnam National Fine Arts Museum, Hanoi",
  "Bảo tàng Mỹ thuật thành phố Hồ Chí Minh": "Ho Chi Minh City Museum of Fine Arts",
  "Bảo tàng Nghệ An - Xô viết Nghệ Tĩnh, tỉnh Nghệ An": "Nghệ An Soviet-Nghệ Tĩnh Museum, Nghệ An Province",
  "Bảo tàng Phòng không - Không quân, Hà Nội": "Air Defense - Air Force Museum, Hanoi",
  "Bảo tàng Pleiku, tỉnh Gia Lai": "Pleiku Museum, Gia Lai Province",
  "Bảo tàng Quảng Nam": "Quảng Nam Museum",
  "Bảo tàng Thành phố Cần Thơ": "Cần Thơ City Museum",
  "Bảo tàng Thành phố Hồ Chí Minh": "Ho Chi Minh City Museum",
  "Bảo tàng Tăng thiết giáp, Hà Nội": "Armored Forces Museum, Hanoi",
  "Bảo tàng Tổng hợp Quảng Ngãi": "Quảng Ngãi General Museum",
  "Bảo tàng Tổng hợp tỉnh Quảng Bình": "Quảng Bình Provincial General Museum",
  "Bảo tàng Tổng hợp tỉnh Trà Vinh": "Trà Vinh Provincial General Museum",
  "Bảo tàng Tổng hợp tỉnh Đồng Tháp": "Đồng Tháp Provincial General Museum",
  "Bảo tàng thành phố Cần Thơ": "Cần Thơ City Museum",
  "Bảo tàng tỉnh An Giang": "An Giang Provincial Museum",
  "Bảo tàng tỉnh Bà Rịa - Vũng Tàu": "Bà Rịa - Vũng Tàu Provincial Museum",
  "Bảo tàng tỉnh Bình Dương": "Bình Dương Provincial Museum",
  "Bảo tàng tỉnh Bình Phước": "Bình Phước Provincial Museum",
  "Bảo tàng tỉnh Bình Thuận": "Bình Thuận Provincial Museum",
  "Bảo tàng tỉnh Bình Định": "Bình Định Provincial Museum",
  "Bảo tàng tỉnh Bạc Liêu": "Bạc Liêu Provincial Museum",
  "Bảo tàng tỉnh Bắc Ninh": "Bắc Ninh Provincial Museum",
  "Bảo tàng tỉnh Gia Lai": "Gia Lai Provincial Museum",
  "Bảo tàng tỉnh Hà Giang": "Hà Giang Provincial Museum",
  "Bảo tàng tỉnh Hà Nam": "Hà Nam Provincial Museum",
  "Bảo tàng tỉnh Hà Tĩnh": "Hà Tĩnh Provincial Museum",
  "Bảo tàng tỉnh Hải Dương": "Hải Dương Provincial Museum",
  "Bảo tàng tỉnh Khánh Hòa": "Khánh Hòa Provincial Museum",
  "Bảo tàng tỉnh Long An": "Long An Provincial Museum",
  "Bảo tàng tỉnh Lào Cai": "Lào Cai Provincial Museum",
  "Bảo tàng tỉnh Lạng Sơn": "Lạng Sơn Provincial Museum",
  "Bảo tàng tỉnh Nam Định": "Nam Định Provincial Museum",
  "Bảo tàng tỉnh Nghệ An": "Nghệ An Provincial Museum",
  "Bảo tàng tỉnh Ninh Bình": "Ninh Bình Provincial Museum",
  "Bảo tàng tỉnh Ninh Thuận": "Ninh Thuận Provincial Museum",
  "Bảo tàng tỉnh Phú Yên": "Phú Yên Provincial Museum",
  "Bảo tàng tỉnh Quảng Nam": "Quảng Nam Provincial Museum",
  "Bảo tàng tỉnh Quảng Ninh": "Quảng Ninh Provincial Museum",
  "Bảo tàng tỉnh Quảng Trị": "Quảng Trị Provincial Museum",
  "Bảo tàng tỉnh Thanh Hóa": "Thanh Hóa Provincial Museum",
  "Bảo tàng tỉnh Thái Bình": "Thái Bình Provincial Museum",
  "Bảo tàng tỉnh Tiền Giang": "Tiền Giang Provincial Museum",
  "Bảo tàng tỉnh Vĩnh Long": "Vĩnh Long Provincial Museum",
  "Bảo tàng tỉnh Vĩnh Phúc": "Vĩnh Phúc Provincial Museum",
  "Bảo tàng tỉnh Yên Bái": "Yên Bái Provincial Museum",
  "Bảo tàng tỉnh Đắk Lắk": "Đắk Lắk Provincial Museum",
  "Bảo tàng tỉnh Đắk Nông": "Đắk Nông Provincial Museum",
  "Bảo tàng tỉnh Đồng Nai": "Đồng Nai Provincial Museum",
  "Bảo tàng tỉnh Đồng Tháp": "Đồng Tháp Provincial Museum",
  "Bảo tàng Điêu khắc Chăm, Đà Nẵng": "Museum of Cham Sculpture, Đà Nẵng",
  "Chùa Bình Lâm, huyện Vị Xuyên, tỉnh Hà Giang": "Bình Lâm Pagoda, Vị Xuyên District, Hà Giang Province",
  "Chùa Bút Tháp, xã Đình Tổ, huyện Thuận Thành, tỉnh Bắc Ninh": "Bút Tháp Pagoda, Đình Tổ Commune, Thuận Thành District, Bắc Ninh Province",
  "Chùa Bảo Ninh Sùng Phúc, huyện Chiêm Hóa, tỉnh Tuyên Quang": "Bảo Ninh Sùng Phúc Pagoda, Chiêm Hóa District, Tuyên Quang Province",
  "Chùa Bắc Biên, phường Bồ Đề, Hà Nội": "Bắc Biên Pagoda, Bồ Đề Ward, Hanoi",
  "Chùa Bổ Đà, Bắc Giang": "Bổ Đà Pagoda, Bắc Giang",
  "Chùa Cung Kiệm - Thượng Phúc tự, xã Nhân Hòa, huyện Quế Võ, tỉnh Bắc Ninh": "Cung Kiệm (Thượng Phúc) Pagoda, Nhân Hòa Commune, Quế Võ District, Bắc Ninh Province",
  "Chùa Côn Sơn, thị xã Chí Linh, tỉnh Hải Dương": "Côn Sơn Pagoda, Chí Linh Town, Hải Dương Province",
  "Chùa Cảnh Lâm, xã Tân Việt, huyện Yên Mỹ, tỉnh Hưng Yên": "Cảnh Lâm Pagoda, Tân Việt Commune, Yên Mỹ District, Hưng Yên Province",
  "Chùa Dâu (Sùng Thiên tự), huyện Gia Lộc, tỉnh Hải Dương": "Dâu Pagoda (Sùng Thiên Temple), Gia Lộc District, Hải Dương Province",
  "Chùa Dâu / Chùa Phi Tướng / Chùa Dàn, Bắc Ninh": "Dâu / Phi Tướng / Dàn Pagoda, Bắc Ninh",
  "Chùa Dâu, phường Thanh Khương, thị xã Thuận Thành, tỉnh Bắc Ninh": "Dâu Pagoda, Thanh Khương Ward, Thuận Thành Town, Bắc Ninh Province",
  "Chùa Dạm, Nam Sơn, Bắc Ninh": "Dạm Pagoda, Nam Sơn, Bắc Ninh",
  "Chùa Giàu, xã Đinh Xá, thành phố Phủ Lý, tỉnh Hà Nam": "Giàu Pagoda, Đinh Xá Commune, Phủ Lý City, Hà Nam Province",
  "Chùa Giám, xã Cẩm Sơn, huyện Cẩm Giàng, tỉnh Hải Dương": "Giám Pagoda, Cẩm Sơn Commune, Cẩm Giàng District, Hải Dương Province",
  "Chùa Hương Lãng, xã Minh Hải, huyện Văn Lâm, tỉnh Hưng Yên": "Hương Lãng Pagoda, Minh Hải Commune, Văn Lâm District, Hưng Yên Province",
  "Chùa Hương Trai, xã Dương Hoà, Hà Nội": "Hương Trai Pagoda, Dương Hòa Commune, Hanoi",
  "Chùa Keo Hành Thiện (Thần Quang tự), xã Xuân Hồng, tỉnh Ninh Bình": "Keo Hành Thiện Pagoda (Thần Quang Temple), Xuân Hồng Commune, Ninh Bình Province",
  "Chùa Keo, xã Duy Nhất, huyện Vũ Thư, tỉnh Thái Bình": "Keo Pagoda, Duy Nhất Commune, Vũ Thư District, Thái Bình Province",
  "Chùa Khám Lạng, huyện Lục Nam, tỉnh Bắc Giang": "Khám Lạng Pagoda, Lục Nam District, Bắc Giang Province",
  "Chùa Linh Sơn, thành phố Quy Nhơn, tỉnh Bình Định": "Linh Sơn Pagoda, Quy Nhơn City, Bình Định Province",
  "Chùa Linh Ứng, huyện Thuận Thành, tỉnh Bắc Ninh": "Linh Ứng Pagoda, Thuận Thành District, Bắc Ninh Province",
  "Chùa Mễ Sở (Diên Phúc tự), huyện Văn Giang, tỉnh Hưng Yên": "Mễ Sở Pagoda (Diên Phúc Temple), Văn Giang District, Hưng Yên Province",
  "Chùa Nghĩa Xá (Viên Quang tự), xã Xuân Trường, tỉnh Ninh Bình": "Nghĩa Xá Pagoda (Viên Quang Temple), Xuân Trường Commune, Ninh Bình Province",
  "Chùa Ngô Xá, huyện Ý Yên, tỉnh Nam Định": "Ngô Xá Pagoda, Ý Yên District, Nam Định Province",
  "Chùa Nhạn Sơn, xã Nhơn Hậu, thị xã An Nhơn, tỉnh Bình Định": "Nhạn Sơn Pagoda, Nhơn Hậu Commune, An Nhơn Town, Bình Định Province",
  "Chùa Nhạn Tháp, xã Mễ Sở, tỉnh Hưng Yên": "Nhạn Tháp Pagoda, Mễ Sở Commune, Hưng Yên Province",
  "Chùa Phúc Nghiêm (chùa Tổ), phường Song Liễu, tỉnh Bắc Ninh": "Phúc Nghiêm Pagoda (Ancestral Pagoda), Song Liễu Ward, Bắc Ninh Province",
  "Chùa Phật Tích, Bắc Ninh": "Phật Tích Pagoda, Bắc Ninh",
  "Chùa Phổ Minh, phường Lộc Vượng, thành phố Nam Định, tỉnh Nam Định": "Phổ Minh Pagoda, Lộc Vượng Ward, Nam Định City, Nam Định Province",
  "Chùa Sùng Khánh, huyện Vị Xuyên, tỉnh Hà Giang": "Sùng Khánh Pagoda, Vị Xuyên District, Hà Giang Province",
  "Chùa Thanh Mai, thị xã Chí Linh, tỉnh Hải Dương": "Thanh Mai Pagoda, Chí Linh Town, Hải Dương Province",
  "Chùa Thiên Mụ, thành phố Huế, tỉnh Thừa Thiên Huế": "Thiên Mụ Pagoda, Huế City, Thừa Thiên Huế Province",
  "Chùa Thượng Nương, thôn Tam Tứ, xã Liêm Hà, tỉnh Ninh Bình": "Thượng Nương Pagoda, Tam Tứ Hamlet, Liêm Hà Commune, Ninh Bình Province",
  "Chùa Thầy, xã Sài Sơn, huyện Quốc Oai, Hà Nội": "Thầy Pagoda, Sài Sơn Commune, Quốc Oai District, Hanoi",
  "Chùa Trà Phương, xã Thụy Hương, huyện Kiến Thụy, thành phố Hải Phòng": "Trà Phương Pagoda, Thụy Hương Commune, Kiến Thụy District, Hai Phong City",
  "Chùa Trăm Gian, xã An Bình, huyện Nam Sách, tỉnh Hải Dương": "Trăm Gian Pagoda, An Bình Commune, Nam Sách District, Hải Dương Province",
  "Chùa Tây Phương, xã Thạch Xá, huyện Thạch Thất, Hà Nội": "Tây Phương Pagoda, Thạch Xá Commune, Thạch Thất District, Hanoi",
  "Chùa Tĩnh Lự, xã Lãng Ngâm, huyện Gia Bình, tỉnh Bắc Ninh": "Tĩnh Lự Pagoda, Lãng Ngâm Commune, Gia Bình District, Bắc Ninh Province",
  "Chùa Vĩnh Nghiêm, huyện Yên Dũng, tỉnh Bắc Giang": "Vĩnh Nghiêm Pagoda, Yên Dũng District, Bắc Giang Province",
  "Chùa Xuân Lũng, xã Xuân Lũng, huyện Lâm Thao, tỉnh Phú Thọ": "Xuân Lũng Pagoda, Xuân Lũng Commune, Lâm Thao District, Phú Thọ Province",
  "Chùa Điều, huyện Bình Lục, tỉnh Hà Nam": "Điều Pagoda, Bình Lục District, Hà Nam Province",
  "Chùa Đào Xuyên, xã Đa Tốn, huyện Gia Lâm, Hà Nội": "Đào Xuyên Pagoda, Đa Tốn Commune, Gia Lâm District, Hanoi",
  "Chùa Đại Bi, xã Dương Hoà, Hà Nội": "Đại Bi Pagoda, Dương Hòa Commune, Hanoi",
  "Chùa Đậu, huyện Thường Tín, thành phố Hà Nội": "Đậu Pagoda, Thường Tín District, Hanoi",
  "Chùa Đọi Sơn, thị xã Duy Tiên, tỉnh Hà Nam": "Đọi Sơn Pagoda, Duy Tiên Town, Hà Nam Province",
  "Chùa Động Ngọ, huyện Thanh Hà, tỉnh Hải Dương": "Động Ngọ Pagoda, Thanh Hà District, Hải Dương Province",
  "Cục Lưu trữ Văn phòng Trung ương Đảng, Hà Nội": "Central Party Office Archives, Hanoi",
  "Di tích Côn Sơn - Kiếp Bạc, Chí Linh, Hải Dương": "Côn Sơn - Kiếp Bạc Relic Site, Chí Linh, Hải Dương",
  "Di tích tháp Pô Rômê, xã Phước Hữu, huyện Ninh Phước, tỉnh Ninh Thuận": "Pô Rômê Tower Relic, Phước Hữu Commune, Ninh Phước District, Ninh Thuận Province",
  "Di tích Động Kính Chủ, Hải Dương": "Kính Chủ Cave Relic, Hải Dương",
  "Kho bạc nhà nước tỉnh Hưng Yên": "Hưng Yên Provincial State Treasury",
  "Khu Di tích Chủ tịch Hồ Chí Minh tại Phủ Chủ tịch, Hà Nội": "President Ho Chi Minh Relic Site at the Presidential Palace, Hanoi",
  "Khu di tích Chùa Đà Quận - Đền Quan Triều, thành phố Cao Bằng": "Đà Quận Pagoda - Quan Triều Temple Relic Site, Cao Bằng City",
  "Khu di tích Cố đô Hoa Lư, Ninh Bình": "Hoa Lư Ancient Capital Relic Site, Ninh Bình",
  "Khu di tích Cố đô Hoa Lư, tỉnh Ninh Bình": "Hoa Lư Ancient Capital Relic Site, Ninh Bình Province",
  "Khu di tích Cổ Loa, xã Cổ Loa, huyện Đông Anh, thành phố Hà Nội": "Cổ Loa Relic Site, Cổ Loa Commune, Đông Anh District, Hanoi",
  "Khu di tích Thành Hoàng Đế, xã Nhơn Hậu, thị xã An Nhơn, tỉnh Bình Định": "Thành Hoàng Đế Citadel Relic Site, Nhơn Hậu Commune, An Nhơn Town, Bình Định Province",
  "Khu di tích lịch sử Lam Kinh, huyện Thọ Xuân, tỉnh Thanh Hóa": "Lam Kinh Historical Relic Site, Thọ Xuân District, Thanh Hóa Province",
  "Khu di tích lịch sử Đền Hùng, thành phố Việt Trì, tỉnh Phú Thọ": "Hùng Kings Temple Historical Relic Site, Việt Trì City, Phú Thọ Province",
  "Khu di tích tưởng niệm Vương triều Mạc, xã Ngũ Đoan, huyện Kiến Thụy, thành phố Hải Phòng": "Mạc Dynasty Memorial Relic Site, Ngũ Đoan Commune, Kiến Thụy District, Hai Phong City",
  "Khu di tích Đền Mẫu Âu Cơ, xã Hiền Lương, huyện Hạ Hòa, tỉnh Phú Thọ": "Mother Âu Cơ Temple Relic Site, Hiền Lương Commune, Hạ Hòa District, Phú Thọ Province",
  "Sưu tập tư nhân An Biên, thành phố Hải Phòng": "An Biên Private Collection, Hai Phong City",
  "Sưu tập tư nhân Lê Thanh Nghĩa, TP Hồ Chí Minh": "Lê Thanh Nghĩa Private Collection, Ho Chi Minh City",
  "Sưu tập tư nhân Lương Hoàng Long, TP Hội An, Quảng Nam": "Lương Hoàng Long Private Collection, Hội An, Quảng Nam",
  "Sưu tập tư nhân Đào Danh Đức, Hà Nội": "Đào Danh Đức Private Collection, Hanoi",
  "Tháp Huệ Quang, chùa Hoa Yên, Khu Di tích Yên Tử, xã Thượng Yên Công, thành phố Uông Bí, tỉnh Quảng Ninh": "Huệ Quang Tower, Hoa Yên Pagoda, Yên Tử Relic Site, Thượng Yên Công Commune, Uông Bí City, Quảng Ninh Province",
  "Tháp Pô Klong Garai, phường Đô Vinh, thành phố Phan Rang - Tháp Chàm, tỉnh Ninh Thuận": "Pô Klong Garai Tower, Đô Vinh Ward, Phan Rang - Tháp Chàm City, Ninh Thuận Province",
  "Trung tâm Bảo tồn Di sản Thăng Long - Hà Nội": "Thăng Long Heritage Conservation Center, Hanoi",
  "Trung tâm Bảo tồn Di tích Cố đô Huế, tỉnh Thừa Thiên Huế": "Hue Monuments Conservation Center, Thừa Thiên Huế Province",
  "Trung tâm Lưu trữ quốc gia III, Cục Văn thư và Lưu trữ nhà nước, Bộ Nội vụ": "National Archives Center III, State Records and Archives Department, Ministry of Home Affairs",
  "Vách núi Phia Tém, xã Bình Long, huyện Hòa An, tỉnh Cao Bằng": "Phia Tém Cliff, Bình Long Commune, Hòa An District, Cao Bằng Province",
  "Vách núi Thành Nam, xã Con Cuông, tỉnh Nghệ An": "Thành Nam Cliff, Con Cuông Commune, Nghệ An Province",
  "Văn Miếu - Quốc Tử Giám, Hà Nội": "Temple of Literature, Hanoi",
  "Văn Miếu Bắc Ninh, phường Đại Phúc, thành phố Bắc Ninh, tỉnh Bắc Ninh": "Bắc Ninh Temple of Literature, Đại Phúc Ward, Bắc Ninh City, Bắc Ninh Province",
  "Điện Kính Thiên, Khu Trung tâm Hoàng thành Thăng Long - Hà Nội": "Kính Thiên Palace, Thăng Long Imperial Citadel, Hanoi",
  "Điện Thái Hòa, Trung tâm Bảo tồn Di tích Cố đô Huế": "Thái Hòa Palace, Hue Monuments Conservation Center",
  "Đình Cầu Không, xã Bắc Lý, tỉnh Ninh Bình": "Cầu Không Communal House, Bắc Lý Commune, Ninh Bình Province",
  "Đình Diềm, xã Hòa Long, thành phố Bắc Ninh, tỉnh Bắc Ninh": "Diềm Communal House, Hòa Long Commune, Bắc Ninh City, Bắc Ninh Province",
  "Đình Nhật Tảo, phường Đông Ngạc, quận Bắc Từ Liêm, Hà Nội": "Nhật Tảo Communal House, Đông Ngạc Ward, Bắc Từ Liêm District, Hanoi",
  "Đình Nội (Đền Lạc Long Quân), thôn Bình Đà, huyện Thanh Oai, Hà Nội": "Nội Communal House (Lạc Long Quân Temple), Bình Đà Hamlet, Thanh Oai District, Hanoi",
  "Đình Thổ Hà, xã Vân Hà, huyện Việt Yên, tỉnh Bắc Giang": "Thổ Hà Communal House, Vân Hà Commune, Việt Yên District, Bắc Giang Province",
  "Đình Trích Sài, phường Bưởi, quận Tây Hồ, Hà Nội": "Trích Sài Communal House, Bưởi Ward, Tây Hồ District, Hanoi",
  "Đền - chùa Bà Tấm, xã Dương Xá, huyện Gia Lâm, Hà Nội": "Bà Tấm Temple-Pagoda, Dương Xá Commune, Gia Lâm District, Hanoi",
  "Đền - chùa Bà Tấm, xã Dương Xá, huyện Gia Lâm, thành phố Hà Nội": "Bà Tấm Temple-Pagoda, Dương Xá Commune, Gia Lâm District, Hanoi",
  "Đền A10, khu đền tháp Mỹ Sơn, huyện Duy Xuyên, tỉnh Quảng Nam": "A10 Temple, Mỹ Sơn Sanctuary, Duy Xuyên District, Quảng Nam Province",
  "Đền An Xá, xã An Viên, huyện Tiên Lữ, tỉnh Hưng Yên": "An Xá Temple, An Viên Commune, Tiên Lữ District, Hưng Yên Province",
  "Đền Quán Thánh, quận Ba Đình, Hà Nội": "Quán Thánh Temple, Ba Đình District, Hanoi",
  "Đền Trấn Vũ, phường Thạch Bàn, quận Long Biên, Hà Nội": "Trấn Vũ Temple, Thạch Bàn Ward, Long Biên District, Hanoi",
  "Đền thờ Hà Tông Mục, xã Tùng Lộc, huyện Can Lộc, tỉnh Hà Tĩnh": "Hà Tông Mục Temple, Tùng Lộc Commune, Can Lộc District, Hà Tĩnh Province",
  "Đền thờ Lê Văn Thịnh, huyện Gia Bình, tỉnh Bắc Ninh": "Lê Văn Thịnh Temple, Gia Bình District, Bắc Ninh Province",
  "Đền thờ Trạng nguyên Giáp Hải, Bắc Giang": "Giáp Hải (Top Laureate) Temple, Bắc Giang",
  "Đền thờ vua Lê Thái Tổ, huyện Nậm Nhùn, tỉnh Lai Châu": "King Lê Thái Tổ Temple, Nậm Nhùn District, Lai Châu Province",
  "Đền Đa Hòa, xã Mễ Sở, tỉnh Hưng Yên": "Đa Hòa Temple, Mễ Sở Commune, Hưng Yên Province",
  "Động Liên Hoa, chùa Phong Phú, phường Tây Hoa Lư, tỉnh Ninh Bình": "Liên Hoa Cave, Phong Phú Pagoda, Tây Hoa Lư Ward, Ninh Bình Province",
  "Ủy ban nhân dân huyện Đăk Tô, tỉnh Kon Tum": "Đăk Tô District People's Committee, Kon Tum Province",
  "Ủy ban nhân dân xã Lạc Đạo, huyện Văn Lâm, tỉnh Hưng Yên": "Lạc Đạo Commune People's Committee, Văn Lâm District, Hưng Yên Province",
};
